backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Bats", "Gloves", "Cleats", "Apparel", "Catcher’s Gear", "Buying Guides"] }
      - { label: "Author", name: "author", widget: "string", default: "Elite Baseball Supply" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }